# Generated by Django 4.0.3 on 2023-07-19 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('import_href', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hat',
            name='wardrobe_location',
            field=models.ForeignKey(db_column='wardrobe_location_id', on_delete=django.db.models.deletion.CASCADE, to='hats_rest.locationvo'),
        ),
    ]
