# Generated by Django 4.0.3 on 2023-07-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_binvo_shoe_bin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='brand',
            new_name='model_name',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='size',
        ),
        migrations.AddField(
            model_name='shoe',
            name='manufacturer',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='url',
            field=models.URLField(default=True, null=True),
        ),
    ]
